name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev
    
    - name: Configure CMake
      run: cmake -S . -B build
    
    - name: Build
      run: cmake --build build
    
    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure
    
     - name: Build with QMake (optional)
      run: |
        qmake observer.pro
        make
        
    - name: Create deb package
      working-directory: ${{github.workspace}}/build
      run: cpack -G DEB
    
    - name: Upload deb package
      uses: actions/upload-artifact@v3
      with:
        name: observer-pattern-deb
        path: build/*.deb
    
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: build/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
