name: Build and Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev
        sudo apt-get install -y debhelper
        
    - name: Build
      run: |
        mkdir build && cd build
        cmake ..
        make
        ctest --output-on-failure
        
    - name: Create DEB package
      run: |
        mkdir -p observer-pkg/usr/local/lib
        cp build/libobserver_pattern.a observer-pkg/usr/local/lib/
        
        mkdir -p observer-pkg/DEBIAN
        cat > observer-pkg/DEBIAN/control <<EOL
        Package: observer-pattern
        Version: 1.0
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: Observer pattern implementation
        EOL
        
        dpkg-deb --build observer-pkg
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: observer-pattern
        path: build/observer-pkg.deb
  
    - name: Build with QMake (optional)
      run: |
        qmake observer.pro
        make
