name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # Разрешение для создания релиза

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev
    
    - name: Configure CMake
      run: cmake -S . -B build
    
    - name: Build
      run: cmake --build build
    
    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure
    
    - name: Create deb package
      working-directory: ${{github.workspace}}/build
      run: cpack -G DEB
    
    - name: Upload deb package
      uses: actions/upload-artifact@v4
      with:
        name: observer-pattern-deb
        path: build/*.deb
        if-no-files-found: error
    
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: build/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
